### ISSUE TITLE
Reconnecting after network outage

### ISSUE THREAD

**Issue by flashtheman** [luin/ioredis#1699] opened 2023-01-06 13:38 UTC
When I develop locally and put my laptop to sleep, or when I just disable the wifi for a minute, then it seems that the redis connection is not being re-established. I'm afraid that this would be fatal for live environments in case such a network outage happens at night. Is there a way to configure the redis client in a way that it's reconnecting automatically? I tried different reconnect strategies, different parameters etc. but never succeeded in re-establishing the connection. This is an example of a configuration that causes the problem:

```
    const redisClient = new Redis({
        host: process.env.REDIS_HOST, username: process.env.REDIS_USERNAME, password: process.env.REDIS_PASSWORD, port: Number(process.env.REDIS_PORT), tls: {},
        reconnectOnError(err) {
            console.log('The following Redis connect error occured:', err, 'trying to reconnect...')
            return true
        }
    })

    redisClient.on('error', function (e) {
        console.error(`Redis error occurred "${e?.message}".`)
    })
    redisClient.on('connect', function () {
        console.error(`Redis connected to server.`)
    })
    redisClient.on('reconnecting', function () {
        console.error(`Redis reconnected to server.`)
    })
    redisClient.on('closed', function (e) {
        console.error(`Redis reconnection closed "${e?.message}".`)
    })
    redisClient.on('closed', function () {
        console.error(`Redis is ready`)
    })
```

I'm using version 6 (also tried version 4) of Redis Cache for Azure.

**Comment by menocomp** [comment] 2023-02-20 04:28
I have the same issue and spent hours debugging and could not get it to run. :(

**Comment by luin** [comment] 2023-02-21 10:37
I think it's a duplicate of https://github.com/luin/ioredis/issues/1706. I'd suggest running a ping command periodically to detect network failover in your app code.

Merged to https://github.com/luin/ioredis/issues/1706

**Closed by luin** 2023-02-21 10:37 UTC
