### ISSUE TITLE
Retrieve item of XRANGE as Buffer

### ISSUE THREAD

**Issue by davidkelley** [luin/ioredis#1540] opened 2022-03-26 06:21 UTC
Hi,

First of all, thanks for the amazing library!

I'm not sure if this is currently possible or not, but we were hoping to store items inside an XRANGE as binary, but there doesn't seem to be a method of retrieving this data from Redis as binary, only utf8 strings. I see that other functions have a Buffer alternative, such as `.getBuffer()` but `.xrange()` does not.

Have I missed something? 🤔

**Comment by luin** [comment] 2022-03-26 06:26
Hi @davidkelley 👋 
`xrangeBuffer` is supported:

<img width="707" alt="CleanShot 2022-03-26 at 14 23 21@2x" src="https://user-images.githubusercontent.com/635902/160227547-2619b630-5f1c-4fab-bd90-6f95bf922b8b.png">

The cause could be `@types/ioredis` doesn't include the declaration for it although the code actually supports it. If you are using ioredis v4.x.x, you may want to upgrade to v5.0.0 as v5.0.0 provides official TypeScript declarations.

**Comment by luin** [comment] 2022-03-30 12:38
Closing this as the question should have been answered.

**Closed by luin** 2022-03-30 12:38 UTC
Labels: question
