### ISSUE TITLE
Does ioredis support Azure cache cluster mode?

### ISSUE THREAD

**Issue by cocobiz** [luin/ioredis#873] opened 2019-05-22 11:22 UTC
We are using Azure Cache in cluster mode，and we have confirmed that there is no configure issue.

Code:
```javascript
const redisClient = new Redis.Cluster([
    {
        port: 6379,
        host: 'xxxxxx.redis.cache.windows.net'
    }
], {
    redisOptions: {
       password: 'xxxxx'
   }
});
```
and then got lots of error when run above code:

```javascript
Reids occurs an error when connecting to a node ReplyError: ERR This instance has cluster support disabled
Redis init occurred error: ClusterAllFailedError: Failed to refresh slots cache.
Redis a node is disconnected
```
---
node: 10.15.0
ioredis: 4.9.5

**Comment by luin** [comment] 2019-05-23 03:07
Haven't tested with Azure cache cluster mode. What do you get for command `cluster slots` from redis-cli connecting to `xxxxxx.redis.cache.windows.net`?

The error "ERR This instance has cluster support disabled" is caused by connecting to a redis server with cluster mode disabled, in which case using `new Redis({host: 'xxxxxx.redis.cache.windows.net', password: 'xxxxxx'})` should connect to the server successfully.

**Comment by cocobiz** [comment] 2019-05-23 04:58
@luin command `cluster slots` also got the same error
```javascript
ERR This instance has cluster support disabled
````

**Comment by luin** [comment] 2019-05-23 07:12
@cocobiz Then it seems that the cluster mode is not enabled. Could you give it a double check?

**Comment by cocobiz** [comment] 2019-05-23 08:55
@luin there are no related settings, and we have decided to using single mode.
thanks a lot :)

**Comment by luin** [comment] 2019-05-23 15:00
OK, I'm closing this for now. Anyone who run into the same issue feel free to reopen this with more details 😄 .

**Closed** 2019-05-25 03:03 UTC

**Comment by shivansh** [comment] 2020-06-11 14:10
I have been facing issues when trying to connect to an Azure redis instance with clustering enabled. Connection to the instance is successful with the following code -
```
const redis = new Redis({
  port: 6380,
  host: hostname,
  password: password,
  tls: true
});

(async () => {
  await redis.set("foo", "bar");
  redis.get("foo", function(err, result) {
    console.log(result);
  });
})();

```

However, when `new Redis.Cluster()` is used the following error is reported -
```
const redis = new Redis.Cluster(
  [
    {
      port: 6380,
      host: hostname
    }
  ],
  {
    redisOptions: {
      password: password
    }
  }
);
```

```
[ioredis] Unhandled error event: ClusterAllFailedError: Failed to refresh slots cache.
    at tryNode (/users/i512663/rediss/node_modules/ioredis/built/cluster/index.js:359:31)
    at /users/i512663/rediss/node_modules/ioredis/built/cluster/index.js:376:21
    at Timeout.<anonymous> (/users/i512663/rediss/node_modules/ioredis/built/cluster/index.js:624:24)
    at Timeout.run (/users/i512663/rediss/node_modules/ioredis/built/utils/index.js:156:22)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:492:7)
```

Running cluster-slots via redis-cli gives the following output -
```
127.0.0.1:6380> cluster slots
1) 1) (integer) 0
   2) (integer) 16383
   3) 1) "10.160.128.7"
      2) (integer) 15001
      3) "3b7f949f58b9bf5ccb3e96a190850e0af2ca68e3"
   4) 1) "10.160.128.7"
      2) (integer) 15000
      3) "1a1dad2346c1b67052af9c13b03c24783d10743d"
```

- - -

node: 12.18.0
ioredis: 4.17.3

**Comment by JeffreyCA** [comment] 2020-06-12 20:31
@shivansh see #1149

**Comment by shivansh** [comment] 2020-06-13 15:51
@JeffreyCA This works, thanks a lot!
