### ISSUE TITLE
is ioredis support redis.setresp(3) ?

### ISSUE THREAD

**Issue by usrtax** [luin/ioredis#1653] opened 2022-09-15 22:16 UTC
https://github.com/redis/redis-specifications/blob/master/protocol/RESP3.md

**Comment by TysonAndre** [comment] 2022-10-18 00:49
Duplicate of #1073 

Not yet, but it looks like it's planned long term

See https://github.com/luin/ioredis/issues/1073#issuecomment-822997967

**Closed by TysonAndre** 2022-10-18 00:49 UTC
