### ISSUE TITLE
Add support for async resources

### ISSUE THREAD

**Issue by cupofjoakim** [luin/ioredis#1191] opened 2020-09-14 06:53 UTC
As a developer needing to maintain context information during asynchronous network calls and ioredis asynchronous nature, we should implement Node Async Hooks' Embedder API to allow proper usage of Async Hooks.

As of today, if you're using async_hooks anywhere in your app (with something like [cls-hooked](https://github.com/Jeff-Lewis/cls-hooked)) and also want to use ioredis there's a chance that you will loose your context information after calling any get or set redis function. This breaks a lot of enterprise requirements, such as logging a correlation id in each application log to understand what request triggered what error.

The maintainer of cls-hooked created a similar issue in https://github.com/Automattic/mongoose/issues/5929 which resulted in a plugin for mongoose, but I'm not sure what an applicable fix would be for this repo.

**Comment by cupofjoakim** [comment] 2020-09-15 10:23
I've created a PR in nodejs/diagnostics to add ioredis as a problematic module in terms of aync_hook compatibility:  https://github.com/nodejs/diagnostics/pull/430

Should be mentioned that there's a really outdated package for node-redis called cls-redis that solved this issue back in the day. async_hooks have gone through a lot of changes since then, so I'm not sure if that is helpful at all.

**Comment by lagnat** [comment] 2020-11-23 20:34
+1

**Comment by lagnat** [comment] 2020-11-23 22:19
Upon second glance, it looks like ioredis might be working fine.  @cupofjoakim Do you have a failing test?  I tried to make a failing test but was not able to.

**Comment by cupofjoakim** [comment] 2020-11-24 08:47
@lagnat I don't, sadly. Our team has moved away from ioredis since we discovered this. At that time it happened if we got to a certain level of concurrent traffic, and not all the time.

To explain it further, if we had two requests being handled at the same time, one of the async contexts originating from a different library on one request would cause the other request to loose its context originating in another library. This happened on the latest node 12 release in the beginning of september.

Might not even be an issue in 14, I can't try it atm. Maybe we should close?

**Comment by lagnat** [comment] 2020-11-24 17:39
@cupofjoakim Based on my limited understanding of how async contexts get lost/mixed, I was not able to make ioredis fail.  I think closing the issue makes sense.  This is what I attempted.
```
Promise.promisifyAll(Redis);
Promise.promisifyAll(Redis.prototype);

const redis = new Redis();

const asyncLocalStorage = new AsyncLocalStorage();

let i = 0;

setInterval(() => {
    const ourCtx = i++;
    asyncLocalStorage.enterWith(ourCtx);
    redis.getAsync('something')
        .then((x) => {
            const ctx = asyncLocalStorage.getStore();
            if (ourCtx != ctx)
                console.log('Got ' + ourCtx + " with asl " + ctx);  // This never happened
        });
}, 0);
```

**Closed** 2020-11-24 20:57 UTC

**Comment by lagnat** [comment] 2023-01-31 03:58
@shashank42 Do you have a way to reproduce the issue?

**Comment by shashank42** [comment] 2023-01-31 20:37
### **No issue with ioredis and any version of node as such**

Not able to reproduce it in a new repo I tried : https://github.com/shashank42/ioredis-als-failure-case
It worked fine. So I suspect, another library is playing bad (specifically [tsoa](https://www.npmjs.com/package/tsoa)).

The problem was clear as I was logging the variable from context right before and after fetching from redis
```

export const getLang = () => {
    return httpContext.get("language");
}

console.log("Before : ", getLang()); // Always gave the right log, eg, "pt"

// Random redis stuff
const redis = await getRedis();
console.log(await redis.get("profile:244"));

console.log("After : ", getLang()); // Always gave _undefined_

```

**Took a few steps and the above test now satisfied**

1. Switch from [als](https://www.npmjs.com/package/asynchronous-local-storage) to [express-http-context](https://www.npmjs.com/package/express-http-context) because the code I modified required namespace which is only exposed in express-http-context
2. Add a monkeypatch usign shimmer
3. Setup express middleware properly as per express-http-context docs and make sure to [bind emitters](https://stackoverflow.com/a/55995352/7157731)

The solution was to write monkeypatch for ioredis similar to work on [cls-redis](https://github.com/othiym23/cls-redis/blob/master/shim.js), also got help from a [shimmer monkeypatch written elsewhere](https://github.com/iopipe/iopipe-js-trace/blob/6c7e6544ca1c3c0f3de0b181385ee4ddcce05dcb/src/plugins/ioredis.js#L47)

**The patch that worked for typescript**

```

var shimmer = require('shimmer');
var ioredis = require('ioredis');
var proto = ioredis && ioredis.Redis && ioredis.Redis.prototype;

function slice(args: any) {
    /**
     * Usefully nerfed version of slice for use in instrumentation. Way faster
     * than using [].slice.call, and maybe putting it in here (instead of the
     * same module context where it will be used) will make it faster by
     * defeating inlining.
     *
     *   http://jsperf.com/array-slice-call-arguments-2
     *
     *  for untrustworthy benchmark numbers. Only useful for copying whole
     *  arrays, and really only meant to be used with the arguments arraylike.
     *
     *  Also putting this comment inside the function in an effort to defeat
     *  inlining.
     */
    var length = args.length, array = [], i;
  
    for (i = 0; i < length; i++) array[i] = args[i];
  
    return array;
  }
 console.log(proto); // Just to check
shimmer.wrap(proto, 'sendCommand', function (send_command: any) {

    return function wrapped(command: any) {
        var args     = slice(arguments);
        var callback = command.resolve;
        var promise = command.promise;

        if (typeof command.resolve === 'function') {
            command.resolve = ns.bind(callback);
        }

        if (command.promise) {
            if (typeof command.promise.finally === 'function') {
              command.promise.finally = ns.bind(promise.finally);
            } else if (typeof command.promise.then === 'function') {
                command.promise.then = ns.bind(promise.then);
            }
          }

        return send_command.apply(this, args);
      };
});

import Redis from 'ioredis'; // Import it properly here to get the advantage of types in typescript
// ... further redis setup code

```

Also important to set up the middleware in your express app like this

```
export const languageMiddleware = async (req: Request, res: Response, next: NextFunction) => {
    if (req.method === "OPTIONS")
    { 
        next();
    } else if (req.i18n) {
        httpContext.ns.bindEmitter(req);
        httpContext.ns.bindEmitter(res);
        httpContext.set("language", "pt");
        next();
    } else {
        next();
    }
    return;
}

var httpContext = require('express-http-context');
app.use(httpContext.middleware);

app.use(languageMiddleware);

//... app.listen.... rest of the application code

```
