### ISSUE TITLE
HGETALL results within pipeline() and within multi() are different

### ISSUE THREAD

**Issue by ionian-wind** [luin/ioredis#226] opened 2016-01-13 14:07 UTC
It seems that the built-in reply transformer for HGETALL command isn't working for transaction response

Example code:
```javascript
redis.hset('test-hash', 'key', 'value').then(function () {
    redis.multi()
        .hgetall('test-hash')
        .exec().then(function (res) {
            console.log('multi', res);
        });
    redis.pipeline()
        .hgetall('test-hash')
        .exec().then(function (res) {
            console.log('pipeline', res);
        });
});
```

Output:
```
pipeline [ [ null, { key: 'value' } ] ]
multi [ [ null, [ 'key', 'value' ] ] ]
```

ioredis version is 1.14.0

Upd: 
Ooops, my bad
Already submitted in #158

**Comment by luin** [comment] 2016-01-13 14:11
duplicate of #158. Will be fixed in the next major version :rocket:

**Closed by luin** 2016-01-13 14:11 UTC
