### ISSUE TITLE
All of a sudden, I'm receiving this error

### ISSUE THREAD

**Issue by thelinuxlich** [luin/ioredis#390] opened 2016-11-02 16:51 UTC
```
[Error: Too many Cluster redirections. Last error: ReplyError: MOVED 6686 10.240.100.31:7000]
```

I have a 6 nodes setup, I saw this in the log of a node:

```
Oct 31 19:04:54 aidax-redis-2 redis-server[1501]: 1501:M 31 Oct 19:04:54.996 * Marking node bd1251b171bf467313c4300d761d92417cbb586f as failing (quorum reached).
Oct 31 19:04:55 aidax-redis-2 redis-server[1501]: 1501:M 31 Oct 19:04:55.439 * Clear FAIL state for node bd1251b171bf467313c4300d761d92417cbb586f: slave is reachable again.
```

I think ioredis is not recovering well alongside the redis cluster(3.2)

**Comment by luin** [comment] 2016-11-03 02:19
Could you please enable the debug mode (`DEBUG=ioredis:* node yourapp.js`) and post the logs during this problem happens here?

**Comment by thelinuxlich** [comment] 2016-11-03 02:36
Ok, I will keep you updated

**Comment by thelinuxlich** [comment] 2016-11-03 17:09
So today it happened again and this is the log with DEBUG:

https://gist.github.com/thelinuxlich/365b8cafc98295b14077a38a44a949a7

**Comment by luin** [comment] 2016-11-04 03:33
When a command is rejected with error `MOVED`, ioredis will update the local slot cache and send the command to the new node. It's strange that the command is sent multiple times to the same node.

**Comment by thelinuxlich** [comment] 2016-11-04 05:06
I'm configuring it to connect with all the 6 nodes, and when this happens, I have to restart the whole process :(

**Comment by thelinuxlich** [comment] 2016-11-06 09:14
Some more info: I'm using Node 5.5 and the redis operations consist of GET, SET, SETEX and EVALSHA scripts(using defineCommand)

**Comment by thelinuxlich** [comment] 2016-11-07 16:19
Is there anymore info I can provide you to help pinpoint the issue?

**Comment by luin** [comment] 2016-11-07 16:36
@thelinuxlich Is this issue related with your environment? If the issue cannot be reproduced with general setups, it would be very helpful to provide the docker files so I can debug the problem locally in exact the same environment as yours. Otherwise is it possible to help me narrow down the possibility where the problem happens.

**Comment by thelinuxlich** [comment] 2016-11-07 16:39
I'm testing with older ioredis versions, let's see

**Comment by thelinuxlich** [comment] 2016-11-07 22:23
Interesting, ioredis 2.0.0 is doing okay

**Comment by luin** [comment] 2016-11-08 02:06
That's strange since there's not much difference between the two versions: https://github.com/luin/ioredis/compare/v2.0.0...v2.4.0. Hmm...

**Comment by thelinuxlich** [comment] 2016-11-08 16:51
Now I can confirm that switching to ioredis 2.0.0 totally mitigates the problem

**Comment by luin** [comment] 2016-11-08 20:41
@thelinuxlich Could you please also test with ioredis v2.1.0 & v2.2.0 so we can know which version was the issue introduced. Thanks a lot 😆

**Comment by thelinuxlich** [comment] 2016-11-17 02:49
After days of testing, can confirm this happens in ioredis 2.2+

**Comment by luin** [comment] 2016-11-17 09:17
That means 2.1.0 doesn't have the problem? Looks like there's no much difference in cluster mode between 2.1.0 & 2.2.0: https://github.com/luin/ioredis/compare/v2.1.0...v2.2.0. Hmm...

**Comment by AVVS** [comment] 2016-11-17 10:03
To me it looks like cluster misconfiguration. the difference is that ioredis create a new node based on report from a cluster node, which tells to ask some new node not from the list - it tries to ask that node, gets another redirect and so on. One would assume that that nodes report wrong ip addresses for some reason and that leads to redirection loops

Other possibility is that response is parsed incorrectly? But I assume it's not the case though

**Comment by thelinuxlich** [comment] 2016-11-18 19:26
Well, it can't be misconfiguration because  I've been using ioredis for more than a year without changes in configuration and all of a sudden when I update from 2.0 to 2.4 this began to happen.

**Comment by AVVS** [comment] 2016-11-18 19:39
@thelinuxlich maybe you are right. The place it can happen is

https://github.com/luin/ioredis/compare/v2.1.0...v2.2.0#diff-ded17b5f6b1633a10701ad5e98a4e3c8R428

**Comment by Aditya-Chowdhry** [comment] 2017-10-01 18:09
Recently used Ioredis cluster in production and got the above-mentioned errors. Just want to check up on the status of the issue. Is it resolved in latest version?

**Comment by luin** [comment] 2017-10-02 09:28
@Aditya-Chowdhry No, the issue hasn't been reproduced in my environment.
@thelinuxlich How did you solve the problem in the end?
@AVVS The link you posted seems to be broken. Which part of code did you mention?

**Comment by AVVS** [comment] 2017-10-02 15:33
`https://github.com/luin/ioredis/compare/v2.1.0...v2.2.0#diff-ded17b5f6b1633a10701ad5e98a4e3c8R428`

Fixed link

**Comment by luin** [comment] 2017-10-03 05:09
@AVVS Thanks for the update. How is this line of code related with the issue?

**Comment by Aditya-Chowdhry** [comment] 2017-10-03 07:55
In my case, I am only getting this same exact error repeatedly

> MOVED 0 xxx.xx.xx.xx:6389

 where the cluster consists of only 4 masters, ports - 6389,6390,6391,6392

I have another cluster consisting of master & slaves for which I am not getting any error.

**Comment by luin** [comment] 2017-10-03 08:39
Was 6389 down while getting the error? Is the issue reproducible?

**Comment by Aditya-Chowdhry** [comment] 2017-10-03 09:38
No 6389 was not down. I am not able to reproduce it locally. Debugging further. Will get back if found something ASAP.

**Comment by Aditya-Chowdhry** [comment] 2017-10-04 07:44
@luin Got the issue. This error that I posted comes when null cache key is passed. I wrote a rough small code to reproduce the issue. 

````
'use strict';
const Redis = require('ioredis');
const CLUSTER_HOST = '127.0.0.1';


const cluster = new Redis.Cluster([{
    port: 6383,
    host: CLUSTER_HOST
}, {
    port: 6384,
    host: CLUSTER_HOST
}]);

let cacheKey = null;
let data = 'Hey this is test data';
console.log('CacheKey', cacheKey);
for(var i = 0; i < 100; ++i) {
	cluster.set(cacheKey, data, function(err, reply){
		if(err) console.log('Error', err);
		if(reply) console.log('Okay set done', reply);
		cluster.expire(cacheKey, 1234, function(err, reply){
			if(err) console.log('Error', err);
			if(reply) console.log('Okay expire done', reply);
			cluster.get(cacheKey, function(err, reply){
				if(err) console.log('Error', err);
				if(reply) console.log('Okay get done', reply);
			});
		});
	});
}

> Error: Too many Cluster redirections. Last error: ReplyError: MOVED 0 127.0.0.1:6380

**Comment by luin** [comment] 2017-10-04 10:02
@Aditya-Chowdhry Just fixed this issue in v3.2.1. Thank you for the example, that helps!

**Comment by tuananh** [comment] 2017-10-04 10:10
@luin one question: why when key `undefined`, you want to calculate slot anyway?

**Comment by luin** [comment] 2017-10-04 11:47
@tuananh `null` and `undefined` are converted to empty strings in ioredis. It makes sense to calculate slot for an empty string.

**Closed** 2017-11-10 12:57 UTC
Labels: wontfix

**Comment by thenitai** [comment] 2017-12-27 17:10
I'm seeing this issue with 3.2.2 in our production environment with 3 redis nodes (different IP's)
