### ISSUE TITLE
Better multi/exec results (suggestion)?

### ISSUE THREAD

**Issue by an-sh** [luin/ioredis#301] opened 2016-05-11 11:37 UTC
Hello.

As for versions 1.x and 2.x-rc transaction multi/exec results are
returned in `[Error, [Error1, Value1], ... ]` format. With promised
based API it looks very confusing, for example:

``` javascript
ioredis.multi().get('key1').get('key2').exec()
  .spread( ([e1, val1], [e2, val2]) => {
    /* NO ERRORS(?) */
  })
  .catch(e => {
    /* ERROR HANDLING */
  });
```

It is unclear what should `e1` and `e2` mean in this context. As far
as i understand, partially applied transaction should happen only when
arguments count is wrong, or command is used on a wrong value type. So
such errors should never occur when redis is used correctly. Will it
be better to have something like this?

``` javascript
ioredis.multi().get('key1').get('key2').exec()
  .spread( (val1, val2) => {
    /* NO ERRORS */
  })
  .catch(e => {
    /* ERROR HANDLING, e may have a field with transaction results
     * like this [ [Error1, Value1], ... ] */
  });
```

**Comment by luin** [comment] 2016-05-12 02:08
Syntax errors (wrong command name or argument count) will just abort the transaction and cause the whole transaction being rejected.

Partially applied transactions are only caused by runtime errors, as you said, apply commands on wrong type keys. In these cases, we should provide an easier way to let people handle the results and errors. The current format `[[err1, val1], [err2, val2]]` will make things clearer on which commands are failed and which commands are success. What's more, this format will force developers to handle the errors explicitly. However I'm not sure if there's any better way to do this.

The way node_redis handle the transaction is feasible to me (returning replies following the format `[res1, err2, res3]`). It would be easier for developers to handle the results, but people have to call `if (results[1] instanceof Error) {}` to check whether the result is an error. I afraid this will lead many developers forgetting handle the errors.

**Comment by an-sh** [comment] 2016-05-12 11:57
Here are more details/reasoning about it.


I did not mention it explicitly, but the main point is to have an
error value constructed even if only one command has failed. So the
following is always true: either you have an error or all results of a
transaction.


So arguments for it:

1. Partially applied transaction is an edge case, that should not
happen if Redis is used correctly (Redis is using this argument too,
to rationalise an absence of rollback support). Still anyone who wants
to handle this edge case can do it, but in an error handling code.

2. It will actually make error handling much easier, as it will be
like any other node API. Something semantically resembling
`Promise.all` and an actual transaction in general. Also in terms of
syntax just a common use of callbacks (first argument check) or
promises (attaching a catch handler).


Argument against:

1. It is just a very big breaking API change.

2. Pipelining is using the same API (explicitly stating that error is
always `null`), on the other hand pipelining has a different
semantics.


Also Redis docs states that it is up to a library how to handle this
situation:

> EXEC returned two-element Bulk string reply where one is an OK code
  and the other an -ERR reply. It's up to the client library to find a
  sensible way to provide the error to the user.


Probably there is more things to consider.


At least could some example like this be added to the documentation:

```javascript
redis.multi().set('key1', 'val1').hget('key1', 'val1').exec()
  .spread( (r1, r2) => {
    // We get here, with the following results:
    // [ null, 'OK' ] [ { [ReplyError: WRONGTYPE Operation against a key holding the wrong kind of value]
    //     name: 'ReplyError',
    //     message: 'WRONGTYPE Operation against a key holding the wrong kind of value' } ]
    console.log(r1, r2);
  })
  .catch(e => {
    // We DON'T get here.
    console.log(e);
  });
```

In my opinion, this very non-intuitive from a promise specification
and transaction meaning points of view (the same to a certain degree
can be applied to node style callbacks).

**Comment by luin** [comment] 2016-05-12 16:14
I agree with you that `[[err1, res1], [err2, res2]]` is non-intuitive. @BridgeAR What do you think about this issue. Currently node_redis and ioredis have different result format for transactions, and I think it would be better to let them use an unified format.

The solution @an-sh suggested (reject the whole transaction when one of the commands in the transaction fails) makes sense to me. We may use two different error classes for `EXECABORT` and partial errors.

**Comment by BridgeAR** [comment] 2016-05-17 11:32
I agree that it would be nice to have a unified format. I also like the idea of @an-sh. As ioredis v.2 is not yet released it could be added there and for node_redis I'm likely going to release a v.3 alpha to get some breaking changes in there and keep support for v.2 at the same time.

So overall :+1:

**Comment by luin** [comment] 2016-05-29 10:15
I decided to release ioredis v2 without changing the transaction result format and do that in ioredis v3 (which I think will be released in one or two months).

**Comment by lo1tuma** [comment] 2016-08-17 11:15
I would also like to see a better transaction result format for the promise-based API.

What do you think about introducing a custom error type, e.g. `PartiallyAppliedTransactionError` which could have additional fields that point exactly to the commands that have been applied of failed, for example:

```js
redis.multi().set('key1', 'val1').hget('key1', 'val1').exec()
    .catch(error => {
        if (error instanceof redis.PartiallyAppliedTransactionError) {
            console.log(error.commandErrors); // ⇨ [null, [ReplyError: WRONGTYPE Operation against a key holding the wrong kind of value]]
            console.log(error.commandResults); // ⇨ ['OK', null]
        }
    });
```

**Closed** 2017-10-30 18:45 UTC
Labels: discussion, wontfix
