### ISSUE TITLE
Unhandled error event: Error: read ECONNRESET at TCP.onStreamRead

### ISSUE THREAD

**Issue by sysopsnw18** [luin/ioredis#1203] opened 2020-10-08 05:52 UTC
Hi,
I am getting below error sometimes. Redis connection gets disconnected sometime. Out of 10 I am facing this issue 2 time. It takes time to reconnect the server and api response time increases from 50-80 msec to 1-2 mins.

Error : Unhandled error event: Error: read ECONNRESET at TCP.onStreamRead

Ioredis client configuration as below:
var redisMasterClient = new IORedis({
                    host: host ,
                    connectTimeout: 1000,
		   password: "password,
                    keepAlive : 1000,
                    retryStrategy: function(times) {
			var delay = Math.min(times * 10, 2000);
                        return delay;
                    },
                    maxRetriesPerRequest: 1
                });

Please help. This is urgent issue on production.

**Comment by mrosendin** [comment] 2020-11-20 18:33
I am also having this issue

**Comment by wshino** [comment] 2020-11-30 06:43
Me too. I'll watch this issue.

**Comment by slaveofcode** [comment] 2021-02-26 05:12
Got the same problem

**Comment by ctrlaltdylan** [comment] 2021-03-02 22:14
same issue, tried reseting the worker, deleting and recreating the redis instance but no luck

**Comment by ctrlaltdylan** [comment] 2021-03-03 13:56
Turns out Heroku's Redis v6 instances are self-signing certificates. Passing `ignoreUnauthorized` to the `tls` options fixed the issue for me. Filing a bug report with Heroku too.

**Comment by kapalkat** [comment] 2021-03-10 14:36
Hey, I have the same. Seems like following PR might resolve that: https://github.com/luin/ioredis/pull/1236.
The question is: when we can expect a merge?

**Comment by luin** [comment] 2021-03-18 19:40
Sorry for the late response. This issue should be fixed in the latest version published in the last week. Closing this. Feel free to reopen if there are any issues.

**Closed by luin** 2021-03-18 19:40 UTC

**Comment by RedfurREBORN** [comment] 2021-07-08 04:38
Im still getting the problem and im on the latest version.

**Comment by RedfurREBORN** [comment] 2021-07-08 04:39
![image](https://user-images.githubusercontent.com/62601155/124863316-3b060380-dffa-11eb-9abb-6b5be19c2976.png)

**Comment by yovanoc** [comment] 2021-07-11 23:16
Getting the problem too

**Comment by cata0309** [comment] 2021-08-06 09:09
I am getting this too

**Comment by andredezzy** [comment] 2021-08-20 02:31
Any news for this issue, I am having the same problem.

**Comment by flyingCrp** [comment] 2021-09-02 09:05
im getting this too 
has any progress for this issue?

**Comment by luin** [comment] 2021-09-02 09:11
Network issues can be the cause of `ECONNRESET` errors. It's in all probability not related to ioredis and the Redis server itself. I'd check the network first by using telnet or something similar in the same network condition of the client to see whether it works.

**Comment by flyingCrp** [comment] 2021-09-06 02:42
i guess,ioredis's `ping`  was broken
because i add a `setInterval` task that send the `ping`  to the redis server at every 15s,now  its work fine. 

> Network issues can be the cause of `ECONNRESET` errors. It's in all probability not related to ioredis and the Redis server itself. I'd check the network first by using telnet or something similar in the same network condition of the client to see whether it works.

**Comment by ren-zhihao** [comment] 2021-10-12 03:51
i am getting this too,
at 6am and 6:15am every day.
![微信截图_20211012115011](https://user-images.githubusercontent.com/63542770/136888343-42e11bce-b8a7-47e6-bec6-a8eb267949e4.png)

**Comment by dopt** [comment] 2021-11-23 02:38
I am getting the same error, any workaround for this?

**Comment by dopt** [comment] 2021-11-23 03:21
I resolved my issue by using the following option

```
const client = new Redis(process.env.REDIS_URL, {
  tls: {
    rejectUnauthorized: false
  }
});
```

Can try if it helps at your side

**Comment by ntedgi** [comment] 2021-12-07 16:41
hi @dopt  do you use AWS elasticCache or self hosted redis instance?
did the problem eventually solved

**Comment by flyingCrp** [comment] 2022-01-14 08:01
> 

i dont understand whats the relationship with this attribute. 
maybe use `setInterval`  send `ping`  to redisserver  is temp solution

**Comment by flyingCrp** [comment] 2022-01-14 08:02
> I resolved my issue by using the following option
> 
> ```
> const client = new Redis(process.env.REDIS_URL, {
>   tls: {
>     rejectUnauthorized: false
>   }
> });
> ```
> 
> Can try if it helps at your side

i dont understand whats the relationship with this attribute. 
maybe use `setInterval`  send `ping`  to redisserver  is temp solution.

**finding the root cause and fixing it is the best solution**

**Comment by jayantasamaddar** [comment] 2022-09-19 01:21
The right way to do this is to handle the error gracefully. The problem seems to be the IORedis client's behaviour of timed disconnect when inactive but it has an auto reconnect option that will keep trying to reconnect.

Use Node.js Event Emitter to handle it. View all events with `client.eventNames()` or see the references below. One can simply log out the `error`, `reconnecting` and `connect` events like this to understand what IORedis is doing in the background.

```
import Redis from 'ioredis';
import dotenv from 'dotenv';
import path from 'path';
dotenv.config({ path: path.resolve(__dirname, '../.env') });

const client = new Redis({
  port: Number(process.env.SESSION_STORE_PORT) || 6379,
  host: process.env.SESSION_STORE_HOSTNAME,
});

// Listen to 'error' events to the Redis connection
client.on('error', error => {
  if (error.code === 'ECONNRESET') {
    console.log('Connection to Redis Session Store timed out.');
  } else console.log(error);
});

// Listen to 'reconnecting' event to Redis
client.on('reconnecting', err => {
  if (client.status === 'reconnecting')
    console.log('Reconnecting to Redis Session Store...');
  else console.log('Error reconnecting to Redis Session Store.');
});

// Listen to the 'connection' event to Redis
client.on('connect', err => {
  if (!err) console.log('Connected to Redis Session Store!');
});

export default client;
```

### References:

- **[IORedis - Connection Events](https://ioredis.readthedocs.io/en/latest/README/#connection-events)**
- **[IORedis - Options available for `new Redis([port], [host], options)`](https://ioredis.readthedocs.io/en/latest/API/)**

**Comment by Felipeex** [comment] 2023-09-04 17:55
Hello, you don't instance radis, when your application starts. you'll instance when you use the radis.

Exemple here:
```js
try {
 await redis.set("test", "test")
} catch (err) {
 console.log("error", err)
} finally {
 redis.quit() // stop connection here, and init other when you need
}
```

**Comment by jayantasamaddar** [comment] 2023-09-04 18:20
> Hello, you don't instance radis, when your application starts. you'll instance when you use the radis.
> 
> Exemple here:
> ```js
> try {
>  await redis.set("test", "test")
> } catch (err) {
>  console.log("error", err)
> } finally {
>  redis.quit() // stop connection here, and init other when you need
> }
> ```

This is okay only when your application is having low throughput into redis. For a medium to higher throughput application, why would you want to open and close connection for every R/W operation and increase your latency per operation? In most cases, you want to keep it open and gracefully handle the error then, unless there's. a security reason why you should not or if it's infrequent use.

**Comment by ShivaBhattacharjee** [comment] 2024-02-24 07:34
Getting the same error

![Screenshot from 2024-02-24 13-04-40](https://github.com/redis/ioredis/assets/95211406/6da7c331-6623-4cd2-8dd9-4f8335fd2a7e)

**Comment by PuffMeow** [comment] 2024-03-17 13:43
There is still this error in 2024...

**Comment by thepranaygupta** [comment] 2024-04-02 04:12
same issue, tried reseting the worker, deleting and recreating the redis instance but no luck

**Comment by babeingineer** [comment] 2024-04-16 02:39
![Untitled](https://github.com/redis/ioredis/assets/152193215/5d5bb0b7-aca6-4093-92e6-0dd4d94f3dc7)
Tried all above solutions but not working....

**Comment by jayantasamaddar** [comment] 2024-04-24 12:38
> The right way to do this is to handle the error gracefully. The problem seems to be the IORedis client's behaviour of timed disconnect when inactive but it has an auto reconnect mechanism that will keep trying to reconnect.
> 
> Use Node.js Event Emitter to handle it. View all events with `client.eventNames()` or see the references below. One can simply log out the `error`, `reconnecting` and `connect` events like this to understand the behaviour described above that IORedis is doing in the background. Consequently, this also handles the irritating error message. Hope this helps!
> 
> ```js
> import Redis from 'ioredis';
> import dotenv from 'dotenv';
> import path from 'path';
> dotenv.config({ path: path.resolve(__dirname, '../.env') });
> 
> const client = new Redis({
>   port: Number(process.env.SESSION_STORE_PORT) || 6379,
>   host: process.env.SESSION_STORE_HOSTNAME,
> });
> 
> // Listen to 'error' events to the Redis connection
> client.on('error', error => {
>   if (error.code === 'ECONNRESET') {
>     console.log('Connection to Redis Session Store timed out.');
>   } else if (error.code === 'ECONNREFUSED') {
>     console.log('Connection to Redis Session Store refused!');
>   } else console.log(error);
> });
> 
> // Listen to 'reconnecting' event to Redis
> client.on('reconnecting', err => {
>   if (client.status === 'reconnecting')
>     console.log('Reconnecting to Redis Session Store...');
>   else console.log('Error reconnecting to Redis Session Store.');
> });
> 
> // Listen to the 'connect' event to Redis
> client.on('connect', err => {
>   if (!err) console.log('Connected to Redis Session Store!');
> });
> 
> export default client;
> ```
> 
> ### References:
> * **[IORedis - Connection Events](https://ioredis.readthedocs.io/en/latest/README/#connection-events)**
> * **[IORedis - Options available for `new Redis([port], [host], options)`](https://ioredis.readthedocs.io/en/latest/API/)**

@babeingineer try this

**Comment by techmedbuddy** [comment] 2024-05-29 18:22
In my case : it is not working : in development mode (http)

so using this helped,
const client = new Redis(process.env.REDIS_URL, {
  tls: {
    rejectUnauthorized: false
  }
});

but in production : remove this

**Comment by OmGarg8700** [comment] 2024-05-29 18:22
In my case : it is not working : in development mode (http)

so using this helped,
const client = new Redis(process.env.REDIS_URL, {
tls: {
rejectUnauthorized: false
}
});

but in production : remove this

**Comment by abdulsamadayoade** [comment] 2024-08-22 00:55
None of the solutions is working for me

**Comment by KingPuiWong** [comment] 2024-11-29 13:23
> None of the solutions is working for me

me too.
