### ISSUE TITLE
Protocol error, got \"À\" as reply type byte. Please report this.

### ISSUE THREAD

**Issue by danielmoonactive** [luin/ioredis#1165] opened 2020-07-20 07:21 UTC
ioredis version: 4.6.0

During cluster failover in production, and in the lab where we can reproduce it, we receive the following error:

`Protocol error, got \"À\" as reply type byte. Please report this.`

As the log says, we are reporting this.

We also suspect this is causing another issue, where the response of request A is returned as part of the response of request B. We are also unsure if this is causing other issues as well.

Please assist.

Thanks

**Comment by marcbachmann** [comment] 2022-03-26 12:10
Thanks for the report.
I don't know whether the issue is actually fixed, but this sounds similar like https://github.com/luin/ioredis/issues/1165. Therefore I'll close this as the other issue contains a reproduction for one edge case.

**Closed by marcbachmann** 2022-03-26 12:10 UTC
