### ISSUE TITLE
Cluster connect issue

### ISSUE THREAD

**Issue by nichliu** [luin/ioredis#191] opened 2015-11-03 21:08 UTC
Redis cluster include 3 master, 3 slave
Redis 3.0.4
Node: 4.2.1
Ubuntu: 14.04

redisNodes include 3 master

No error output, Also no results output.
key 'test' exist with value 'hello'

I noticed some times 'ready' been output 8 times on screen, some times only show 1 time

Here is the code
var redis = new Redis.Cluster(redisNodes);

redis.on("error", function (err) {
    console.error("Error " + err);
});

redis.on('connect', function () {
    console.log('ready');
    redis.get('test',function(err,res){
        if(err) console.log(err)
        console.log(res)
    })
});

**Comment by luin** [comment] 2015-11-04 02:47
Closing this since it's a duplicate of #192.

**Closed by luin** 2015-11-04 02:47 UTC
