### ISSUE TITLE
AWS Elasticache + TLS + Hostname Verification

### ISSUE THREAD

**Issue by jordantdavis** [luin/ioredis#754] opened 2018-12-04 16:04 UTC
## Tested Using

* Node.js v10.13.0
* ioredis v4.2.3
* AWS Clustered Redis Elasticache (3 nodes, in-transit and at-rest encryption enabled)

## Problem

When connecting to a Redis cluster, a list of nodes (`host` and `port` combinations) are given.
In the cluster connection logic, the list of node hostnames are then resolved to IP addresses.
For the nodes that have successfully had hostnames resolved to IP addresses, the logic then
overwrites the given `host` for that node with the resolved IP address.  Normally this would not be
an issue, but when connecting to a Redis cluster via TLS (such as AWS encrypted Elasticache) this
can cause issues with Node.js' built-in TLS hostname verification.  Basically, if the IP address of
the node does not appear in the certificate received from the server, then the hostname verification
step will fail causing the connection to fail.

## Example

Running the following code:

```js
const Redis = require('ioredis');

const nodes = [{
    host: 'clustercfg.xxx.use1.cache.amazonaws.com',
    port: '6379',
}];

const options = {
    redisOptions: {
        tls: {}
    }
}

const cluster = new Redis.Cluster(nodes, options);

cluster.set('test-key', 'test-value');

cluster.get('test-key', function (err, res) {
    console.log(res);

    if (err) {
        console.error(err)
    }

    cluster.disconnect()
});
```

ran with `DEBUG=ioredis:* node index.js` produces the following logs:

```
ioredis:cluster status: [empty] -> connecting +0ms
  ioredis:cluster resolved hostname clustercfg.xxx.use1.cache.amazonaws.com to IP aaa.bbb.ccc.ddd +47ms
  ioredis:cluster:connectionPool Reset with [ { host: 'aaa.bbb.ccc.ddd', port: 6379 } ] +0ms
  ioredis:cluster:connectionPool Connecting to aaa.bbb.ccc.ddd:6379 as master +3ms
  ioredis:redis status[aaa.bbb.ccc.ddd:6379]: [empty] -> wait +0ms
  ioredis:cluster getting slot cache from aaa.bbb.ccc.ddd:6379 +7ms
  ioredis:redis status[aaa.bbb.ccc.ddd:6379]: wait -> connecting +1ms
  ioredis:redis queue command[aaa.bbb.ccc.ddd:6379]: 0 -> cluster([ 'slots' ]) +1ms
  ioredis:cluster:subscriber selected a subscriber aaa.bbb.ccc.ddd:6379 +0ms
  ioredis:redis status[aaa.bbb.ccc.ddd:6379 (ioredisClusterSubscriber)]: [empty] -> wait +0ms
  ioredis:cluster:subscriber started +1ms
  ioredis:connection error: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: IP: aaa.bbb.ccc.ddd is not in the cert's list:  +0ms
  ioredis:redis status[aaa.bbb.ccc.ddd:6379]: connecting -> close +111ms
  ioredis:connection skip reconnecting because `retryStrategy` is not a function +2ms
  ioredis:redis status[aaa.bbb.ccc.ddd:6379]: close -> end +1ms
  ioredis:cluster:subscriber subscriber has left, selecting a new one... +111ms
  ioredis:redis status[aaa.bbb.ccc.ddd:6379 (ioredisClusterSubscriber)]: wait -> close +1ms
  ioredis:connection skip reconnecting since the connection is manually closed. +1ms
  ioredis:redis status[aaa.bbb.ccc.ddd:6379 (ioredisClusterSubscriber)]: close -> end +0ms
  ioredis:cluster:subscriber selecting subscriber failed since there is no node discovered in the cluster yet +1ms
  ioredis:cluster status: connecting -> close +114ms
  ioredis:cluster status: close -> reconnecting +0ms
[ioredis] Unhandled error event: ClusterAllFailedError: Failed to refresh slots cache.
    at tryNode (/Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/ioredis/built/cluster/index.js:319:31)
    at /Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/ioredis/built/cluster/index.js:335:21
    at redis.cluster.utils_1.timeout (/Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/ioredis/built/cluster/index.js:551:24)
    at run (/Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/ioredis/built/utils/index.js:150:22)
    at tryCatcher (/Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/standard-as-callback/lib/utils.js:10:19)
    at /Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/standard-as-callback/index.js:31:35
    at process._tickCallback (internal/process/next_tick.js:68:7)
  ioredis:cluster:connectionPool Reset with [] +118ms
  ioredis:cluster connecting failed: Error: None of startup nodes is available +2ms
  ioredis:cluster Cluster is disconnected. Retrying after 102ms +105ms
  ioredis:cluster status: reconnecting -> connecting +0ms
  ioredis:cluster resolved hostname clustercfg.xxx.use1.cache.amazonaws.com to IP aaa.bbb.ccc.ddd +2ms
  ioredis:cluster:connectionPool Reset with [ { host: 'aaa.bbb.ccc.ddd', port: 6379 } ] +108ms
  ioredis:cluster:connectionPool Connecting to aaa.bbb.ccc.ddd:6379 as master +0ms
  ioredis:redis status[aaa.bbb.ccc.ddd:6379]: [empty] -> wait +110ms
  ioredis:cluster:subscriber a new node is discovered and there is no subscriber, selecting a new one... +110ms
  ioredis:cluster:subscriber selected a subscriber aaa.bbb.ccc.ddd:6379 +1ms
  ioredis:redis status[aaa.bbb.ccc.ddd:6379 (ioredisClusterSubscriber)]: [empty] -> wait +1ms
  ioredis:cluster getting slot cache from aaa.bbb.ccc.ddd:6379 +2ms
  ioredis:redis status[aaa.bbb.ccc.ddd:6379]: wait -> connecting +0ms
  ioredis:redis queue command[aaa.bbb.ccc.ddd:6379]: 0 -> cluster([ 'slots' ]) +0ms
  ioredis:redis status[aaa.bbb.ccc.ddd:6379 (ioredisClusterSubscriber)]: wait -> close +0ms
  ioredis:connection skip reconnecting since the connection is manually closed. +112ms
  ioredis:redis status[aaa.bbb.ccc.ddd:6379 (ioredisClusterSubscriber)]: close -> end +1ms
  ioredis:cluster:subscriber selected a subscriber aaa.bbb.ccc.ddd:6379 +1ms
  ioredis:redis status[aaa.bbb.ccc.ddd:6379 (ioredisClusterSubscriber)]: [empty] -> wait +0ms
  ioredis:cluster:subscriber started +0ms
  ioredis:connection error: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: IP: aaa.bbb.ccc.ddd is not in the cert's list:  +99ms
  ioredis:redis status[aaa.bbb.ccc.ddd:6379]: connecting -> close +99ms
  ioredis:connection skip reconnecting because `retryStrategy` is not a function +0ms
  ioredis:redis status[aaa.bbb.ccc.ddd:6379]: close -> end +0ms
  ioredis:cluster:subscriber subscriber has left, selecting a new one... +99ms
  ioredis:redis status[aaa.bbb.ccc.ddd:6379 (ioredisClusterSubscriber)]: wait -> close +0ms
  ioredis:connection skip reconnecting since the connection is manually closed. +0ms
  ioredis:redis status[aaa.bbb.ccc.ddd:6379 (ioredisClusterSubscriber)]: close -> end +0ms
  ioredis:cluster:subscriber selecting subscriber failed since there is no node discovered in the cluster yet +0ms
  ioredis:cluster status: connecting -> close +100ms
  ioredis:cluster status: close -> reconnecting +0ms
[ioredis] Unhandled error event: ClusterAllFailedError: Failed to refresh slots cache.
    at tryNode (/Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/ioredis/built/cluster/index.js:319:31)
    at /Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/ioredis/built/cluster/index.js:335:21
    at redis.cluster.utils_1.timeout (/Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/ioredis/built/cluster/index.js:551:24)
    at run (/Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/ioredis/built/utils/index.js:150:22)
    at tryCatcher (/Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/standard-as-callback/lib/utils.js:10:19)
    at /Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/standard-as-callback/index.js:31:35
    at process._tickCallback (internal/process/next_tick.js:68:7)
  ioredis:cluster:connectionPool Reset with [] +102ms
  ioredis:cluster Got error Error: None of startup nodes is available when reconnecting. Ignoring... +1ms
  ioredis:cluster Cluster is disconnected. Retrying after 104ms +107ms
  ioredis:cluster status: reconnecting -> connecting +0ms
```

where `clustercfg.xxx.use1.cache.amazonaws.com` is the cluster hostname and `aaa.bbb.ccc.ddd` is the
IP address the hostname resolves to.

Note the following debug log message:

```
ioredis:connection error: Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: IP: aaa.bbb.ccc.ddd is not in the cert's list:  +0ms
```

## Workaround

My current workaround is to bypass the TLS hostname verification step with a custom
`checkServerIdentity` function:

```js
const Redis = require('ioredis');

const nodes = [{
    host: 'clustercfg.xxx.use1.cache.amazonaws.com',
    port: '6379',
}];

const options = {
    redisOptions: {
        tls: {
            checkServerIdentity: (servername, cert) => {
                // skip certificate hostname validation
                return undefined;
            },
        }
    }
}

const cluster = new Redis.Cluster(nodes, options);

cluster.set('aws', 'test');

cluster.get('aws', function (err, res) {
    console.log(res);

    if (err) {
        console.error(err)
    }

    cluster.disconnect()
});
```

## Additional Notes

I also experimented with changing part of the cluster connection logic
(`resolveStartupNodeHostnames`) so that it does not overwrite the `host` with the resolved IP
address.  I changed it to the following:

```js
resolveStartupNodeHostnames() {
        if (!Array.isArray(this.startupNodes) || this.startupNodes.length === 0) {
            return Promise.reject(new Error('`startupNodes` should contain at least one node.'));
        }
        const startupNodes = util_1.normalizeNodeOptions(this.startupNodes);
        const hostnames = util_1.getUniqueHostnamesFromOptions(startupNodes);
        if (hostnames.length === 0) {
            return Promise.resolve(startupNodes);
        }
        return Promise.all(hostnames.map((hostname) => this.dnsLookup(hostname))).then((ips) => {
            // change made here
            // rough implementation not overwriting the hosts
            return startupNodes;
        });
    }
```

and I was able to connect to the cluster using the first code example I gave.

## Questions

1. Is there a specific reason that the hosts given when defining the Redis cluster configuration are
replaced by their resolved IP addresses when connecting?
2. Could the connection logic be changed to use hostnames instead of IP address to connect?
3. If #2 is not possible could we add a configuration option to disable overwriting the configured
hostnames with their IP addresses on connection?

**Comment by hendrixroa** [comment] 2018-12-05 03:00
Review security groups inbound rules, or check if is accessible your cluster

**Comment by jordantdavis** [comment] 2018-12-05 16:20
I do not believe this is an issue with security groups.  I am able to connect to the cluster and obtain a certificate.  

The issue is that the connection to the cluster is being made using an IP address instead of the given hostname and the certificate does not contain the IP address as an alternative name, so the TLS hostname verification step fails.  I can get around this issue with a custom `resolveStartupNodeHostnames`, but it is less secure.

**Comment by jordantdavis** [comment] 2018-12-10 01:58
Thank you for the suggestion @luin.  I gave it a try with my sample code above, but it looks like I'm still unable to successfully connect to the cluster via TLS.  I'm still getting the following error: 

```
[ioredis] Unhandled error event: ClusterAllFailedError: Failed to refresh slots cache.
```

I added a `console.log` to the `dnsLookup` override and I'm not seeing any console output, so the override does not seem to be having an effect.  It looks like my example code is failing to establish a TLS connection with the given "cluster config" node and it is subsequently failing to run the `CLUSTER SLOTS` command.  

I think this may be because there is a separate, un-overrideable DNS lookup that is performed on the given "cluster config" node hostname and that IP address is then used to attempt a TLS connection with the "cluster config" node.  I know it is possible to connect to the Elasticache "cluster config" node using a hostname instead of an IP address (with my rough change to the library above), but I'm not sure if that is something Redis is capable of or just Elasticache.

I'd be happy to help add the functionality to make that initial connection using a hostname instead of a looked up IP address if you think it fits here.

Thoughts?

**Comment by luin** [comment] 2018-12-10 17:31
That strange. I tried on my machine connecting to an encrypted Elasticache instance with `dnsLookup` option successfully. The related code is here: https://github.com/luin/ioredis/blob/master/lib/cluster/index.ts#L710. The process of resolving hostnames to IPs only happens during the initial connection, which should be able to be overridden by the `dnsLookup` option.

**Comment by jordandavis-asurion** [comment] 2018-12-17 03:19
The reason the `dnsLookup` override was not working is because I placed it inside the `redisOptions` field instead of at the top level of options.  I also did not previously see that the `dnsLookup` override is used in the `resolveStartupNodeHostnames` function within the cluster connection logic, but I can confirm that my override happens.  My code now looks like this:

```
const Redis = require('ioredis');

const nodes = [{
    host: 'clustercfg.xxx.use1.cache.amazonaws.com',
    port: '6379',
}];

const options = {
    dnsLookup: (address, callback) => callback(null, address),
    redisOptions: {
        tls: {}
    }
}

const cluster = new Redis.Cluster(nodes, options);

cluster.set('aws', 'test');

cluster.get('aws', function (err, res) {
    console.log(res);

    if (err) {
        console.error(err)
    }

    cluster.disconnect()
});
```

When I run this code sometimes it connects and runs successfully.  Most of the time, however, I receive debug logs like this:

```
ioredis:cluster status: [empty] -> connecting +0ms
  ioredis:cluster resolved hostname clustercfg.xxx.use1.cache.amazonaws.com to IP clustercfg.xxx.use1.cache.amazonaws.com +3ms
  ioredis:cluster:connectionPool Reset with [ { host:
  ioredis:cluster:connectionPool      'clustercfg.xxx.use1.cache.amazonaws.com',
  ioredis:cluster:connectionPool     port: 6379 } ] +0ms
  ioredis:cluster:connectionPool Connecting to clustercfg.xxx.use1.cache.amazonaws.com:6379 as master +2ms
  ioredis:redis status[clustercfg.xxx.use1.cache.amazonaws.com:6379]: [empty] -> wait +0ms
  ioredis:cluster getting slot cache from clustercfg.xxx.use1.cache.amazonaws.com:6379 +5ms
  ioredis:redis status[clustercfg.xxx.use1.cache.amazonaws.com:6379]: wait -> connecting +1ms
  ioredis:redis queue command[clustercfg.xxx.use1.cache.amazonaws.com:6379]: 0 -> cluster([ 'slots' ]) +0ms
  ioredis:cluster:subscriber selected a subscriber clustercfg.xxx.use1.cache.amazonaws.com:6379 +0ms
  ioredis:redis status[clustercfg.xxx.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: [empty] -> wait +1ms
  ioredis:cluster:subscriber started +0ms
  ioredis:redis status[aaa.bbb.ccc.ddd:6379]: connecting -> connect +986ms
  ioredis:redis write command[aaa.bbb.ccc.ddd:6379]: 0 -> info([]) +1ms
[ioredis] Unhandled error event: ClusterAllFailedError: Failed to refresh slots cache.
    at tryNode (/Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/ioredis/built/cluster/index.js:319:31)
    at /Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/ioredis/built/cluster/index.js:335:21
    at Timeout.redis.cluster.utils_1.timeout (/Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/ioredis/built/cluster/index.js:551:24)
    at Timeout.run (/Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/ioredis/built/utils/index.js:150:22)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  ioredis:cluster:connectionPool Reset with [] +1s
  ioredis:cluster:connectionPool Disconnect clustercfg.xxx.use1.cache.amazonaws.com:6379 because the node does not hold any slot +1ms
  ioredis:redis status[aaa.bbb.ccc.ddd:6379]: connect -> ready +85ms
  ioredis:connection send 1 commands in offline queue +0ms
  ioredis:redis queue command[aaa.bbb.ccc.ddd:6379]: 0 -> cluster([ 'slots' ]) +0ms
  ioredis:redis status[aaa.bbb.ccc.ddd:6379]: ready -> close +2ms
  ioredis:connection skip reconnecting since the connection is manually closed. +2ms
  ioredis:redis status[aaa.bbb.ccc.ddd:6379]: close -> end +0ms
  ioredis:cluster:subscriber subscriber has left, selecting a new one... +1s
  ioredis:redis status[clustercfg.xxx.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: wait -> close +1ms
  ioredis:connection skip reconnecting since the connection is manually closed. +1ms
  ioredis:redis status[clustercfg.xxx.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: close -> end +0ms
  ioredis:cluster:subscriber selecting subscriber failed since there is no node discovered in the cluster yet +1ms
  ioredis:cluster status: connecting -> close +1s
  ioredis:cluster status: close -> reconnecting +0ms
  ioredis:cluster connecting failed: Error: None of startup nodes is available +0ms
  ioredis:cluster Cluster is disconnected. Retrying after 102ms +103ms
  ioredis:cluster status: reconnecting -> connecting +0ms
  ioredis:cluster resolved hostname clustercfg.xxx.use1.cache.amazonaws.com to IP clustercfg.xxx.use1.cache.amazonaws.com +0ms
  ioredis:cluster:connectionPool Reset with [ { host:
  ioredis:cluster:connectionPool      'clustercfg.xxx.use1.cache.amazonaws.com',
  ioredis:cluster:connectionPool     port: 6379 } ] +176ms
  ioredis:cluster:connectionPool Connecting to clustercfg.xxx.use1.cache.amazonaws.com:6379 as master +0ms
  ioredis:redis status[clustercfg.xxx.use1.cache.amazonaws.com:6379]: [empty] -> wait +105ms
  ioredis:cluster:subscriber a new node is discovered and there is no subscriber, selecting a new one... +105ms
  ioredis:cluster:subscriber selected a subscriber clustercfg.xxx.use1.cache.amazonaws.com:6379 +0ms
  ioredis:redis status[clustercfg.xxx.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: [empty] -> wait +0ms
  ioredis:cluster getting slot cache from clustercfg.xxx.use1.cache.amazonaws.com:6379 +2ms
  ioredis:redis status[clustercfg.xxx.use1.cache.amazonaws.com:6379]: wait -> connecting +1ms
  ioredis:redis queue command[clustercfg.xxx.use1.cache.amazonaws.com:6379]: 0 -> cluster([ 'slots' ]) +0ms
  ioredis:redis status[clustercfg.xxx.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: wait -> close +0ms
  ioredis:connection skip reconnecting since the connection is manually closed. +106ms
  ioredis:redis status[clustercfg.xxx.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: close -> end +0ms
  ioredis:cluster:subscriber selected a subscriber clustercfg.xxx.use1.cache.amazonaws.com:6379 +1ms
  ioredis:redis status[clustercfg.xxx.use1.cache.amazonaws.com:6379 (ioredisClusterSubscriber)]: [empty] -> wait +0ms
  ioredis:cluster:subscriber started +1ms
[ioredis] Unhandled error event: ClusterAllFailedError: Failed to refresh slots cache.
    at tryNode (/Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/ioredis/built/cluster/index.js:319:31)
    at /Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/ioredis/built/cluster/index.js:335:21
    at Timeout.redis.cluster.utils_1.timeout (/Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/ioredis/built/cluster/index.js:551:24)
    at Timeout.run (/Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/ioredis/built/utils/index.js:150:22)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  ioredis:cluster:connectionPool Reset with [] +1s
  ioredis:cluster:connectionPool Disconnect clustercfg.xxx.use1.cache.amazonaws.com:6379 because the node does not hold any slot +0ms
  ioredis:connection error: Error: Client network socket disconnected before secure TLS connection was established +1s
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! encrypted-ec-ioredis@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the encrypted-ec-ioredis@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jdavis/.npm/_logs/2018-12-17T03_10_37_935Z-debug.log
```

Did you see anything like this?  Is my new code any different from the code you tested with?

Thanks!

**Comment by jordantdavis** [comment] 2018-12-18 03:06
I added a `console.log` to the function you referenced:

```
dnsLookup(hostname) {
    return new Promise((resolve, reject) => {
        console.log(this.options.dnsLookup.toString());

        this.options.dnsLookup(hostname, (err, address) => {
            if (err) {
                debug('failed to resolve hostname %s to IP: %s', hostname, err.message);
                reject(err);
            } else {
                debug('resolved hostname %s to IP %s', hostname, address);
                resolve(address);
            }
        });
    });
}
```

and I see this output:

```
> encrypted-ec-ioredis@1.0.0 start /Users/jdavis/workspace/experiments/encrypted-ec-ioredis
> node index.js

(address, callback) => callback(null, address)
(address, callback) => callback(null, address)
(address, callback) => callback(null, address)
(address, callback) => callback(null, address)
test
```

which is expected.  That is also the function I provided in the `dnsLookup` options override.  Additionally, I have ran the same script from yesterday many times tonight and I have not seen the same error message as last night.  I have not seen the script error out a single time tonight so far either.

That is what you expected to seen, correct?

**Comment by jordantdavis** [comment] 2018-12-18 14:46
Just adding some additional logs I see when running the script with `dnsLookup` override:

```
> encrypted-ec-ioredis@1.0.0 start /Users/jdavis/workspace/experiments/encrypted-ec-ioredis
> node index.js

[ioredis] Unhandled error event: ClusterAllFailedError: Failed to refresh slots cache.
    at tryNode (/Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/ioredis/built/cluster/index.js:319:31)
    at /Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/ioredis/built/cluster/index.js:335:21
    at Timeout.redis.cluster.utils_1.timeout (/Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/ioredis/built/cluster/index.js:551:24)
    at Timeout.run (/Users/jdavis/workspace/experiments/encrypted-ec-ioredis/node_modules/ioredis/built/utils/index.js:150:22)
    at ontimeout (timers.js:438:13)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
test
```

Sometimes I will see that error, but eventually it connects to the cluster.

**Comment by luin** [comment] 2018-12-18 17:10
> That is what you expected to see, correct?
Yes, that is. It seems the `dnsLookup` option solves your issue.

> Sometimes I will see that error, but eventually it connects to the cluster.
That should be another issue I think. Does it accurs without `dnsLookup`?

**Comment by jordantdavis** [comment] 2018-12-18 19:34
> That should be another issue I think. Does it accurs without dnsLookup?

I do not remember seeing that error without `dnsLookup`.  In those cases, I override the `checkServerIdentity` function in the `redisOptions.tls` config to ignore the hostname verification for the certificate (the original problem + workaround).

If this is something you would like help looking into just let me know!

I appreciate you donating your time to helping me find a solution to my issue.  Thanks!

**Closed** 2019-01-28 00:19 UTC
Labels: wontfix

**Comment by renatomariscal** [comment] 2022-04-25 23:19
Hi, I got here for trying to to understand the reasoning behind the instruction: https://github.com/luin/ioredis#special-note-aws-elasticache-clusters-with-tls which looks suspicious to me, as that doesn't look like a valid dns lookup implementation, for returning something else than IP.

From reading this thread and the code, it seems like the issue is that https://github.com/luin/ioredis/blob/3bf300a1c99ae4cf8038930c45e19ebd68db222e/lib/cluster/index.ts#L1023-L1030 does an early DNS lookup, and uses the result to connect later in the code.

So, by the time it attempt to connect, it doesn't have the service name to validate.

So short-circuiting the early dns lookup by returning the same name, will pass the actual hostname to NodeJS TLS instead of IP, so it knows what server names to validate against.

Is there a value on doing this early DNS lookup? If so, aren't we loosing it this bypass?

Have you considered some alternatives, like saving the hostname to be used as `servername` in the TLS connection, or maybe passing the `dns.lookup` option there instead of calling it?

Thanks!

**Comment by jiyanhbo** [comment] 2022-04-28 05:24
Under the existing framework, we firstly convert host to ipaddress, then pass ipaddress to create connection pool object. 

When tls is enabled, ipaddress used in connection pool object will fail the tls connection set up since hostname is expected. The suggested solution in readme through bypassing dnslookup is hard to understand for most of users.  How about we address the issue as below
1) When tls is enabled, make sure host passed to cluster constructor is hostname instead of ipaddress
2) remove the logic to convert host to ipaddress & pass host to create connection pool object

I tested the above change and it works for both tls & non-tls scenarios.

**Comment by devSajan** [comment] 2024-01-04 09:36
I am getting the same error `Hostname/IP does not match certificate's altnames:`
