### ISSUE TITLE
Missing hiredis module causes hang on ioredis module load

### ISSUE THREAD

**Issue by jedwardsaviata** [luin/ioredis#45] opened 2015-05-26 15:02 UTC
I have an error that crops up from time to time where a missing hiredis module results in my node program hanging. I traced it down to the `require('hiredis')` line in the *ioredis/lib/parsers/hiredis.js* file.

When wrapped in a `try...catch` block, an error is thrown and the program exits, otherwise the program hangs with no additional output.

**Comment by luin** [comment] 2015-05-26 15:07
Could you show me your code causing the error?

**Comment by jedwardsaviata** [comment] 2015-05-26 16:13
It was simply hanging during the import. As soon as I added the `try...catch` then removed it, everything started working correctly, so I am unable to reproduce it now.

Here is the code surrounding the import. There is only one module import being performed before the ioredis import:

```coffeescript
#!/usr/bin/env coffee

console.log "Starting script."

_ = require 'lodash'
console.log "Lodash ready."

Redis = require 'ioredis'
console.log "Redis module loaded."
                                                                                                                                          
durations = require 'durations'
```

**Comment by luin** [comment] 2015-05-26 16:30
I don't think there's any problem when requiring ioredis without hiredis installed since `require('hiredis')` is wrapped in a `try`/`catch`.
I'm closing this issue. However if you can reproduce the problem, feel free to open this issue again.

**Closed by luin** 2015-05-26 16:30 UTC

**Comment by jedwardsaviata** [comment] 2015-05-26 16:52
I'll admit that was what really surprised me. The fact that there was a `try / catch` already in place. However, the hang actually occurs when the *hiredis* module is being required, so the hang is within the body of the `try` portion before any error has been encountered. This may end up being something I need to raise on the *hiredis-node* repository instead of here if I can reproduce it.

In any case, here are some additional details just in case.

Here is my modified (added try/catch and logging) version of *ioredis/lib/parsers/hiredis.js*

```
'use strict';

console.log("hiredis> load dependencies...");
var events = require('events');
console.log("hiredis> loaded events");
var util = require('util');
console.log("hiredis> loaded util");
var hiredis;
try {
  console.log("hiredis> preparing to load the hiredis module...");
  hiredis = require('hiredis');
  console.log("hiredis> loaded hiredis");
}
catch (error) {
  console.log("Error loading the hiredis module:", error);
}
var ReplyError = require('../reply_error');
console.log("hiredis> loaded ReplyError");                                                                                                
console.log("hiredis> setting up module...");
```


Here is the output with the above modifications in place.

```
hiredis> load dependencies...
hiredis> loaded events
hiredis> loaded util
Error loading the hiredis module: { [Error: Cannot find module 'hiredis'] code: 'MODULE_NOT_FOUND' }
hiredis> loaded ReplyError
hiredis> setting up module...
ioredis> loaded hiredis
ioredis> all dependencies loaded. Setting up the module...
base redis module loaded
reply-error loaded
bluebird loaded
cluster loaded
Redis module loaded.
Redis cliet created.
/home/jedwards/aviata/campaign-builder-import/node_modules/ioredis/lib/parsers/hiredis.js:33
  this.reader = new hiredis.Reader({
                           ^
TypeError: Cannot read property 'Reader' of undefined
  at HiredisReplyParser.reset (/home/jedwards/aviata/campaign-builder-import/node_modules/ioredis/lib/parsers/hiredis.js:33:28)
  at new HiredisReplyParser (/home/jedwards/aviata/campaign-builder-import/node_modules/ioredis/lib/parsers/hiredis.js:24:8)
  at Redis.exports.initParser (/home/jedwards/aviata/campaign-builder-import/node_modules/ioredis/lib/redis/prototype/parser.js:18:22)
  at Socket.<anonymous> (/home/jedwards/aviata/campaign-builder-import/node_modules/ioredis/lib/redis/event_handler.js:24:10)
  at Socket.g (events.js:199:16)
  at Socket.emit (events.js:129:20)
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:991:10)
```

**Comment by Ehesp** [comment] 2016-05-20 08:06
Also had this issue, had to `npm i --save hiredis` to sort it for me.
