### ISSUE TITLE
Redis latency (30 seconds) on initial request

### ISSUE THREAD

**Issue by jegsar** [luin/ioredis#529] opened 2017-10-07 14:35 UTC
The first request I make to my redis cluster each time the application starts takes a long time, sometimes more then 30 seconds. Ever request after that is measured in ms. Is this expected? Should I just be doing a command every time the server starts so the first user action isn't delayed?

Or am I doing something wrong?
When my node app initializes I do the following.
```
var conf = require('../config');
var Redis = require('ioredis');
var cluster = new Redis.Cluster(conf.redis.servers,{
  "redisOptions": {
    "showFriendlyErrorStack": true
  }
});
module.exports = cluster;
```

The first request is normally something like 
```
return redis.smembers('key').then(...)
```
To be clear the result is normally less then 20 elements and this in dev env where there is no other operations running on either the application or Redis servers.

Currently on `-- ioredis@3.1.4 however it was happening with older versions also.

**Comment by luin** [comment] 2017-10-07 17:10
Please enable the debug mode to see whether the logs help.

**Comment by jegsar** [comment] 2017-10-07 17:29
Interestingly when i set `DEBUG=ioredis:*` it works significantly better however 1 time it still took a while.

```"C:\Program Files\nodejs\node.exe" C:\CBDrive\src\circleblack-js\node_modules\mocha\bin\_mocha  C:\CBDrive\src\circleblack-js\test\api\securities\create-update-spec.js
// This is where the application starts.
Sat, 07 Oct 2017 17:21:04 GMT ioredis:cluster status: [empty] -> connecting
Sat, 07 Oct 2017 17:21:04 GMT ioredis:redis status[app-devinone.circleblack.com:8000]: [empty] -> wait
Sat, 07 Oct 2017 17:21:04 GMT ioredis:redis status[app-devinone.circleblack.com:8001]: [empty] -> wait
Sat, 07 Oct 2017 17:21:04 GMT ioredis:redis status[app-devinone.circleblack.com:8002]: [empty] -> wait
Sat, 07 Oct 2017 17:21:04 GMT ioredis:cluster getting slot cache from app-devinone.circleblack.com:8002
Sat, 07 Oct 2017 17:21:04 GMT ioredis:redis status[app-devinone.circleblack.com:8002]: wait -> connecting
Sat, 07 Oct 2017 17:21:04 GMT ioredis:redis queue command[0] -> cluster(slots)
Sat, 07 Oct 2017 17:21:04 GMT ioredis:redis status[app-devinone.circleblack.com:8001]: wait -> connecting
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis status[54.152.161.202:8001]: connecting -> connect
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis write command[0] -> info()
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis status[54.152.161.202:8002]: connecting -> connect
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis write command[0] -> info()
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis status[54.152.161.202:8001]: connect -> ready
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis status[54.152.161.202:8002]: connect -> ready
Sat, 07 Oct 2017 17:21:05 GMT ioredis:connection send 1 commands in offline queue
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis write command[0] -> cluster(slots)
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis status[app-devinone.circleblack.com:8000]: wait -> close
Sat, 07 Oct 2017 17:21:05 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis status[app-devinone.circleblack.com:8000]: close -> end
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis status[10.7.0.132:8002]: [empty] -> wait
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis status[54.152.161.202:8000]: [empty] -> wait
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis status[54.152.161.202:8001]: [empty] -> wait
Sat, 07 Oct 2017 17:21:05 GMT ioredis:cluster status: connecting -> connect
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis status[10.7.0.132:8002]: wait -> connecting
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis queue command[0] -> cluster(info)
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis status[54.152.161.202:8002]: ready -> close
Sat, 07 Oct 2017 17:21:05 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis status[54.152.161.202:8002]: close -> end
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis status[54.152.161.202:8001]: ready -> close
Sat, 07 Oct 2017 17:21:05 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis status[54.152.161.202:8001]: close -> end
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis status[54.152.161.202:8001]: wait -> connecting
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis status[54.152.161.202:8001]: connecting -> connect
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis write command[0] -> info()
[2017-10-07 13:21:05.882] [INFO] api - [POST] [/securities] [371d881c-28e6-4fed-8f6e-817ea3e2450d] [Authenticating] email: ds@cb.test IP: ::ffff:127.0.0.1 [T:13 A:2 Q:0 F:11]
[2017-10-07 13:21:05.882] [DEBUG] orm - [auth] [validateSession] [validating] // This is the first request to Redis
Sat, 07 Oct 2017 17:21:05 GMT ioredis:redis status[54.152.161.202:8001]: connect -> ready
Sat, 07 Oct 2017 17:21:15 GMT ioredis:connection error: Error: connect ETIMEDOUT
Sat, 07 Oct 2017 17:21:15 GMT ioredis:redis status[10.7.0.132:8002]: connecting -> close
Sat, 07 Oct 2017 17:21:15 GMT ioredis:connection skip reconnecting because `retryStrategy` is not a function
Sat, 07 Oct 2017 17:21:15 GMT ioredis:redis status[10.7.0.132:8002]: close -> end
Sat, 07 Oct 2017 17:21:15 GMT ioredis:cluster getting slot cache from 54.152.161.202:8001
Sat, 07 Oct 2017 17:21:15 GMT ioredis:redis write command[0] -> cluster(slots)
Sat, 07 Oct 2017 17:21:15 GMT ioredis:redis status[10.7.0.132:8001]: [empty] -> wait
Sat, 07 Oct 2017 17:21:15 GMT ioredis:redis status[54.152.161.202:8002]: [empty] -> wait
Sat, 07 Oct 2017 17:21:15 GMT ioredis:delayqueue send 1 commands in failover queue
Sat, 07 Oct 2017 17:21:15 GMT ioredis:redis queue command[0] -> cluster(info)
Sat, 07 Oct 2017 17:21:15 GMT ioredis:redis status[54.152.161.202:8001]: ready -> close
Sat, 07 Oct 2017 17:21:15 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Sat, 07 Oct 2017 17:21:15 GMT ioredis:redis status[54.152.161.202:8001]: close -> end
Sat, 07 Oct 2017 17:21:15 GMT ioredis:redis status[10.7.0.132:8001]: wait -> connecting
Sat, 07 Oct 2017 17:21:16 GMT ioredis:cluster getting slot cache from 10.7.0.132:8001
Sat, 07 Oct 2017 17:21:16 GMT ioredis:redis queue command[0] -> cluster(slots)
Sat, 07 Oct 2017 17:21:17 GMT ioredis:cluster getting slot cache from 54.152.161.202:8000
Sat, 07 Oct 2017 17:21:17 GMT ioredis:redis status[54.152.161.202:8000]: wait -> connecting
Sat, 07 Oct 2017 17:21:17 GMT ioredis:redis queue command[0] -> cluster(slots)
Sat, 07 Oct 2017 17:21:17 GMT ioredis:redis status[54.152.161.202:8000]: connecting -> connect
Sat, 07 Oct 2017 17:21:17 GMT ioredis:redis write command[0] -> info()
Sat, 07 Oct 2017 17:21:17 GMT ioredis:redis status[54.152.161.202:8000]: connect -> ready
Sat, 07 Oct 2017 17:21:17 GMT ioredis:connection send 1 commands in offline queue
Sat, 07 Oct 2017 17:21:17 GMT ioredis:redis write command[0] -> cluster(slots)
Sat, 07 Oct 2017 17:21:17 GMT ioredis:redis status[54.152.161.202:8001]: [empty] -> wait
Sat, 07 Oct 2017 17:21:17 GMT ioredis:redis status[10.7.0.132:8000]: [empty] -> wait
Sat, 07 Oct 2017 17:21:17 GMT ioredis:delayqueue send 1 commands in failover queue
Sat, 07 Oct 2017 17:21:17 GMT ioredis:redis queue command[0] -> cluster(info)
Sat, 07 Oct 2017 17:21:17 GMT ioredis:redis status[54.152.161.202:8000]: ready -> close
Sat, 07 Oct 2017 17:21:17 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Sat, 07 Oct 2017 17:21:17 GMT ioredis:redis status[54.152.161.202:8000]: close -> end
Sat, 07 Oct 2017 17:21:25 GMT ioredis:connection error: Error: connect ETIMEDOUT
Sat, 07 Oct 2017 17:21:25 GMT ioredis:redis status[10.7.0.132:8001]: connecting -> close
Sat, 07 Oct 2017 17:21:25 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Sat, 07 Oct 2017 17:21:25 GMT ioredis:redis status[10.7.0.132:8001]: close -> end
Sat, 07 Oct 2017 17:21:25 GMT ioredis:redis status[54.152.161.202:8002]: wait -> connecting
Sat, 07 Oct 2017 17:21:25 GMT ioredis:redis status[54.152.161.202:8002]: connecting -> connect
Sat, 07 Oct 2017 17:21:25 GMT ioredis:redis write command[0] -> info()
Sat, 07 Oct 2017 17:21:25 GMT ioredis:redis status[54.152.161.202:8002]: connect -> ready
Sat, 07 Oct 2017 17:21:26 GMT ioredis:cluster getting slot cache from 10.7.0.132:8000
Sat, 07 Oct 2017 17:21:26 GMT ioredis:redis status[10.7.0.132:8000]: wait -> connecting
Sat, 07 Oct 2017 17:21:26 GMT ioredis:redis queue command[0] -> cluster(slots)
// starts working here
```

**Comment by jegsar** [comment] 2017-10-07 17:41
Interesting when I set `DEBUG=ioredis:*` it seems to work better most of the time but is sometimes still slow.

Here is a log where 2.2.2.2 is the external ip of the remote redis server and 1.1.1.1 is the internal ip which is not directly accessible. What I really don't understand is how enabling debug helps the situation.

```"C:\Program Files\nodejs\node.exe" C:\CBDrive\src\circleblack-js\node_modules\mocha\bin\_mocha C:\CBDrive\src\test\api\securities\create-update-spec.js
Sat, 07 Oct 2017 17:29:54 GMT ioredis:cluster status: [empty] -> connecting
Sat, 07 Oct 2017 17:29:54 GMT ioredis:redis status[url:8000]: [empty] -> wait
Sat, 07 Oct 2017 17:29:54 GMT ioredis:redis status[url:8001]: [empty] -> wait
Sat, 07 Oct 2017 17:29:54 GMT ioredis:redis status[url:8002]: [empty] -> wait
Sat, 07 Oct 2017 17:29:54 GMT ioredis:cluster getting slot cache from url:8002
Sat, 07 Oct 2017 17:29:54 GMT ioredis:redis status[url:8002]: wait -> connecting
Sat, 07 Oct 2017 17:29:54 GMT ioredis:redis queue command[0] -> cluster(slots)
Sat, 07 Oct 2017 17:29:54 GMT ioredis:redis status[url:8000]: wait -> connecting
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[2.2.2.2:8002]: connecting -> connect
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis write command[0] -> info()
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[2.2.2.2:8000]: connecting -> connect
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis write command[0] -> info()
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[2.2.2.2:8002]: connect -> ready
Sat, 07 Oct 2017 17:29:55 GMT ioredis:connection send 1 commands in offline queue
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis write command[0] -> cluster(slots)
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[2.2.2.2:8000]: connect -> ready
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[url:8001]: wait -> close
Sat, 07 Oct 2017 17:29:55 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[url:8001]: close -> end
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[1.1.1.1:8002]: [empty] -> wait
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[2.2.2.2:8000]: [empty] -> wait
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[2.2.2.2:8001]: [empty] -> wait
Sat, 07 Oct 2017 17:29:55 GMT ioredis:cluster status: connecting -> connect
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[2.2.2.2:8002]: ready -> close
Sat, 07 Oct 2017 17:29:55 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[2.2.2.2:8002]: close -> end
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[2.2.2.2:8000]: ready -> close
Sat, 07 Oct 2017 17:29:55 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[2.2.2.2:8000]: close -> end
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[1.1.1.1:8002]: wait -> connecting
[2017-10-07 13:29:55.876] [INFO] api - [POST] [/securities] [7f5c8fdf-6eae-4396-95bb-bc444e9b8f72] [Authenticating] 
[2017-10-07 13:29:55.876] [DEBUG] orm - [auth] [validateSession] [validating]
Sat, 07 Oct 2017 17:29:55 GMT ioredis:cluster getting slot cache from 2.2.2.2:8000
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[2.2.2.2:8000]: wait -> connecting
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis queue command[0] -> cluster(slots)
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[2.2.2.2:8000]: connecting -> connect
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis write command[0] -> info()
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[2.2.2.2:8000]: connect -> ready
Sat, 07 Oct 2017 17:29:55 GMT ioredis:connection send 1 commands in offline queue
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis write command[0] -> cluster(slots)
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[2.2.2.2:8002]: [empty] -> wait
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[1.1.1.1:8000]: [empty] -> wait
Sat, 07 Oct 2017 17:29:55 GMT ioredis:delayqueue send 1 commands in failover queue
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[2.2.2.2:8001]: wait -> connecting
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis queue command[0] -> cluster(info)
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[2.2.2.2:8000]: ready -> close
Sat, 07 Oct 2017 17:29:55 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[2.2.2.2:8000]: close -> end
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[2.2.2.2:8001]: connecting -> connect
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis write command[0] -> info()
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[2.2.2.2:8001]: connect -> ready
Sat, 07 Oct 2017 17:29:55 GMT ioredis:connection send 1 commands in offline queue
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis write command[0] -> cluster(info)
Sat, 07 Oct 2017 17:29:55 GMT ioredis:cluster status: connect -> ready
Sat, 07 Oct 2017 17:29:55 GMT ioredis:cluster send 1 commands in offline queue
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis status[1.1.1.1:8000]: wait -> connecting
Sat, 07 Oct 2017 17:29:55 GMT ioredis:redis queue command[0] -> expire(sessions:test-token:entitlements,900)
Sat, 07 Oct 2017 17:30:05 GMT ioredis:connection error: Error: connect ETIMEDOUT
Sat, 07 Oct 2017 17:30:05 GMT ioredis:redis status[1.1.1.1:8002]: connecting -> close
Sat, 07 Oct 2017 17:30:05 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Sat, 07 Oct 2017 17:30:05 GMT ioredis:redis status[1.1.1.1:8002]: close -> end
Sat, 07 Oct 2017 17:30:05 GMT ioredis:redis status[2.2.2.2:8002]: wait -> connecting
Sat, 07 Oct 2017 17:30:05 GMT ioredis:redis status[2.2.2.2:8002]: connecting -> connect
Sat, 07 Oct 2017 17:30:05 GMT ioredis:redis write command[0] -> info()
Sat, 07 Oct 2017 17:30:05 GMT ioredis:redis status[2.2.2.2:8002]: connect -> ready
Sat, 07 Oct 2017 17:30:05 GMT ioredis:connection error: Error: connect ETIMEDOUT
Sat, 07 Oct 2017 17:30:05 GMT ioredis:redis status[1.1.1.1:8000]: connecting -> close
Sat, 07 Oct 2017 17:30:05 GMT ioredis:connection skip reconnecting because `retryStrategy` is not a function
Sat, 07 Oct 2017 17:30:05 GMT ioredis:redis status[1.1.1.1:8000]: close -> end
Sat, 07 Oct 2017 17:30:06 GMT ioredis:cluster getting slot cache from 2.2.2.2:8002
Sat, 07 Oct 2017 17:30:06 GMT ioredis:redis write command[0] -> cluster(slots)
Sat, 07 Oct 2017 17:30:06 GMT ioredis:redis status[1.1.1.1:8002]: [empty] -> wait
Sat, 07 Oct 2017 17:30:06 GMT ioredis:redis status[2.2.2.2:8000]: [empty] -> wait
Sat, 07 Oct 2017 17:30:06 GMT ioredis:delayqueue send 1 commands in failover queue
Sat, 07 Oct 2017 17:30:06 GMT ioredis:redis queue command[0] -> expire(sessions:test-token:entitlements,900)
Sat, 07 Oct 2017 17:30:06 GMT ioredis:redis status[2.2.2.2:8002]: ready -> close
Sat, 07 Oct 2017 17:30:06 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Sat, 07 Oct 2017 17:30:06 GMT ioredis:redis status[2.2.2.2:8002]: close -> end
Sat, 07 Oct 2017 17:30:06 GMT ioredis:cluster getting slot cache from 2.2.2.2:8000
Sat, 07 Oct 2017 17:30:06 GMT ioredis:redis status[2.2.2.2:8000]: wait -> connecting
Sat, 07 Oct 2017 17:30:06 GMT ioredis:redis queue command[0] -> cluster(slots)
Sat, 07 Oct 2017 17:30:06 GMT ioredis:redis status[2.2.2.2:8000]: connecting -> connect
Sat, 07 Oct 2017 17:30:06 GMT ioredis:redis write command[0] -> info()
Sat, 07 Oct 2017 17:30:06 GMT ioredis:redis status[2.2.2.2:8000]: connect -> ready
Sat, 07 Oct 2017 17:30:06 GMT ioredis:connection send 1 commands in offline queue
Sat, 07 Oct 2017 17:30:06 GMT ioredis:redis write command[0] -> cluster(slots)
Sat, 07 Oct 2017 17:30:06 GMT ioredis:redis status[1.1.1.1:8002]: wait -> close
Sat, 07 Oct 2017 17:30:06 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Sat, 07 Oct 2017 17:30:06 GMT ioredis:redis status[1.1.1.1:8002]: close -> end
Sat, 07 Oct 2017 17:30:06 GMT ioredis:redis status[2.2.2.2:8002]: [empty] -> wait
Sat, 07 Oct 2017 17:30:06 GMT ioredis:redis status[1.1.1.1:8000]: [empty] -> wait
Sat, 07 Oct 2017 17:30:06 GMT ioredis:delayqueue send 1 commands in failover queue
Sat, 07 Oct 2017 17:30:06 GMT ioredis:redis status[1.1.1.1:8000]: wait -> connecting
Sat, 07 Oct 2017 17:30:06 GMT ioredis:redis queue command[0] -> expire(sessions:test-token:entitlements,900)
Sat, 07 Oct 2017 17:30:06 GMT ioredis:redis status[2.2.2.2:8000]: ready -> close
Sat, 07 Oct 2017 17:30:06 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Sat, 07 Oct 2017 17:30:06 GMT ioredis:redis status[2.2.2.2:8000]: close -> end
Sat, 07 Oct 2017 17:30:16 GMT ioredis:connection error: Error: connect ETIMEDOUT
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis status[1.1.1.1:8000]: connecting -> close
Sat, 07 Oct 2017 17:30:16 GMT ioredis:connection skip reconnecting because `retryStrategy` is not a function
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis status[1.1.1.1:8000]: close -> end
Sat, 07 Oct 2017 17:30:16 GMT ioredis:cluster getting slot cache from 2.2.2.2:8002
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis status[2.2.2.2:8002]: wait -> connecting
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis queue command[0] -> cluster(slots)
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis status[2.2.2.2:8002]: connecting -> connect
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis write command[0] -> info()
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis status[2.2.2.2:8002]: connect -> ready
Sat, 07 Oct 2017 17:30:16 GMT ioredis:connection send 1 commands in offline queue
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis write command[0] -> cluster(slots)
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis status[1.1.1.1:8002]: [empty] -> wait
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis status[2.2.2.2:8000]: [empty] -> wait
Sat, 07 Oct 2017 17:30:16 GMT ioredis:delayqueue send 1 commands in failover queue
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis write command[0] -> expire(sessions:test-token:entitlements,900)
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis status[2.2.2.2:8002]: ready -> close
Sat, 07 Oct 2017 17:30:16 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis status[2.2.2.2:8002]: close -> end
Sat, 07 Oct 2017 17:30:16 GMT ioredis:cluster command expire is moved to 2.2.2.2:8000
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis status[2.2.2.2:8000]: wait -> connecting
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis queue command[0] -> expire(sessions:test-token:entitlements,900)
Sat, 07 Oct 2017 17:30:16 GMT ioredis:cluster getting slot cache from 2.2.2.2:8000
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis queue command[0] -> cluster(slots)
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis status[2.2.2.2:8000]: connecting -> connect
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis write command[0] -> info()
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis status[2.2.2.2:8000]: connect -> ready
Sat, 07 Oct 2017 17:30:16 GMT ioredis:connection send 2 commands in offline queue
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis write command[0] -> expire(sessions:test-token:entitlements,900)
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis write command[0] -> cluster(slots)
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis status[1.1.1.1:8002]: wait -> close
Sat, 07 Oct 2017 17:30:16 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis status[1.1.1.1:8002]: close -> end
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis status[2.2.2.2:8002]: [empty] -> wait
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis status[1.1.1.1:8000]: [empty] -> wait
[2017-10-07 13:30:16.472] [INFO] api - [POST] [/securities] [7f5c8fdf-6eae-4396-95bb-bc444e9b8f72] [Authenticating] Session Validated
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis status[1.1.1.1:8000]: wait -> connecting
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis queue command[0] -> smembers(sessions:test-token:entitlements)
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis status[2.2.2.2:8000]: ready -> close
Sat, 07 Oct 2017 17:30:16 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Sat, 07 Oct 2017 17:30:16 GMT ioredis:redis status[2.2.2.2:8000]: close -> end
[2017-10-07 13:30:25.894] [DEBUG] orm - [auth] [validateSession] [validating]
Sat, 07 Oct 2017 17:30:25 GMT ioredis:redis queue command[0] -> expire(sessions:test-token:entitlements,900)
Sat, 07 Oct 2017 17:30:26 GMT ioredis:connection error: Error: connect ETIMEDOUT
Sat, 07 Oct 2017 17:30:26 GMT ioredis:redis status[1.1.1.1:8000]: connecting -> close
Sat, 07 Oct 2017 17:30:26 GMT ioredis:connection skip reconnecting because `retryStrategy` is not a function
Sat, 07 Oct 2017 17:30:26 GMT ioredis:redis status[1.1.1.1:8000]: close -> end
Sat, 07 Oct 2017 17:30:26 GMT ioredis:cluster getting slot cache from 2.2.2.2:8002
Sat, 07 Oct 2017 17:30:26 GMT ioredis:redis status[2.2.2.2:8002]: wait -> connecting
Sat, 07 Oct 2017 17:30:26 GMT ioredis:redis queue command[0] -> cluster(slots)
Sat, 07 Oct 2017 17:30:26 GMT ioredis:redis status[2.2.2.2:8002]: connecting -> connect
Sat, 07 Oct 2017 17:30:26 GMT ioredis:redis write command[0] -> info()
Sat, 07 Oct 2017 17:30:26 GMT ioredis:redis status[2.2.2.2:8002]: connect -> ready
Sat, 07 Oct 2017 17:30:26 GMT ioredis:connection send 1 commands in offline queue
Sat, 07 Oct 2017 17:30:26 GMT ioredis:redis write command[0] -> cluster(slots)
Sat, 07 Oct 2017 17:30:26 GMT ioredis:redis status[1.1.1.1:8002]: [empty] -> wait
Sat, 07 Oct 2017 17:30:26 GMT ioredis:redis status[2.2.2.2:8000]: [empty] -> wait
Sat, 07 Oct 2017 17:30:26 GMT ioredis:delayqueue send 2 commands in failover queue
Sat, 07 Oct 2017 17:30:26 GMT ioredis:redis status[2.2.2.2:8000]: wait -> connecting
Sat, 07 Oct 2017 17:30:26 GMT ioredis:redis queue command[0] -> smembers(sessions:test-token:entitlements)
Sat, 07 Oct 2017 17:30:26 GMT ioredis:redis queue command[0] -> expire(sessions:test-token:entitlements,900)
Sat, 07 Oct 2017 17:30:26 GMT ioredis:redis status[2.2.2.2:8000]: connecting -> connect
Sat, 07 Oct 2017 17:30:26 GMT ioredis:redis write command[0] -> info()
Sat, 07 Oct 2017 17:30:26 GMT ioredis:redis status[2.2.2.2:8002]: ready -> close
Sat, 07 Oct 2017 17:30:26 GMT ioredis:connection skip reconnecting since the connection is manually closed.
Sat, 07 Oct 2017 17:30:26 GMT ioredis:redis status[2.2.2.2:8002]: close -> end
Sat, 07 Oct 2017 17:30:26 GMT ioredis:redis status[2.2.2.2:8000]: connect -> ready
Sat, 07 Oct 2017 17:30:26 GMT ioredis:connection send 2 commands in offline queue
Sat, 07 Oct 2017 17:30:26 GMT ioredis:redis write command[0] -> smembers(sessions:test-token:entitlements)
Sat, 07 Oct 2017 17:30:26 GMT ioredis:redis write command[0] -> expire(sessions:test-token:entitlements,900)
[2017-10-07 13:30:26.665] [INFO] api - [POST] [/securities] [7f5c8fdf-6eae-4396-95bb-bc444e9b8f72] [Authenticating] Entitlements Gathered```

**Comment by luin** [comment] 2017-10-08 14:52
Your app had some troubles connecting to some of the nodes (see the timeout errors in the logs), and that's the cause of the issue.

**Comment by jegsar** [comment] 2017-10-08 15:13
Looking at the log I agree though I don't understand why it would..
I do know that when using the CLI there are no issues.

Also it seems to work considerably better when I have enabled DEBUG=ioredis:* which is very confusing.

**Comment by luin** [comment] 2017-10-23 16:31
I'm closing this since it seems not related with ioredis. Feel free to reopen this issue if the problem still exists.

**Closed by luin** 2017-10-23 16:31 UTC
