### ISSUE TITLE
ioredis blpop command does not work in clustered redis instance

### ISSUE THREAD

**Issue by manasa-ei** [luin/ioredis#850] opened 2019-04-25 18:28 UTC
I am using redis cluster instance as below:

```javascript
var client = new Redis.Cluster([{
          port: 6380,
          host: '127.0.0.1'
        }, {
          port: 6381,
          host: '127.0.0.1'
        }, {
          port: 6382,
          host: '127.0.0.1'
        }, {
          port: 6383,
          host: '127.0.0.1'
        }, {
          port: 6384,
          host: '127.0.0.1'
        }, {
          port: 6385,
          host: '127.0.0.1'
        }], {
          maxRedirections: 1 // This one changed intentionally so that issue can reproduced at the earliest
        });


client.blpop('{q}:email:jobs', 0, console.log) // I issued this command
```

Inside sendCommand method I have issued a console log so as to see which command is being issued as below:

```javascript
Redis.prototype.sendCommand = function (command, stream) {
    console.log('Inside sendCommand method:', command)
```

Got the output as below:
Note: I have placed only blpop command which I have issued and ignore all other commands.
Inside sendCommand method:

```
Command {
  name: 'blpop',
  transformed: true,
  isCustomCommand: false,
  replyEncoding: 'utf8',
  errorStack: undefined,
  args: [ '{q}:email:jobs', '0' ],
  callback: [Function: bound consoleCall],
  resolve: [Function],
  reject: [Function],
  promise: Promise { <pending> },
  keys: [ '{q}:email:jobs' ],
  slot: 11958,
  __is_reject_overwritten: true }
```

Inside sendCommand method:
```
Command {
  name: 'blpop',
  transformed: true,
  isCustomCommand: false,
  replyEncoding: 'utf8',
  errorStack: undefined,
  args: [ '{q}:email:jobs', '0' ],
  callback: [Function: bound consoleCall],
  resolve: [Function],
  reject: [Function],
  promise: Promise { <pending> },
  keys: [ '{q}:email:jobs' ],
  slot: 11958,
  __is_reject_overwritten: true }
```

err is: 

```
{ ReplyError: MOVED 11958 127.0.0.1:6382
    at parseError (/Users/manasamishra/xlabprojects/manas-fork/redis-cluster-ioredis/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/manasamishra/xlabprojects/manas-fork/redis-cluster-ioredis/node_modules/redis-parser/lib/parser.js:302:14) command: { name: 'blpop', args: [ '{q}:email:jobs', '0' ] } }
Error: Too many Cluster redirections. Last error: ReplyError: MOVED 11958 127.0.0.1:6382
    at Cluster.handleError (/Users/manasamishra/xlabprojects/manas-fork/redis-cluster-ioredis/node_modules/ioredis/built/cluster/index.js:534:38)
    at Command.command.reject (/Users/manasamishra/xlabprojects/manas-fork/redis-cluster-ioredis/node_modules/ioredis/built/cluster/index.js:412:23)
    at Redis.exports.returnError (/Users/manasamishra/xlabprojects/manas-fork/redis-cluster-ioredis/node_modules/ioredis/built/redis/parser.js:61:26)
    at JavascriptRedisParser.returnError (/Users/manasamishra/xlabprojects/manas-fork/redis-cluster-ioredis/node_modules/ioredis/built/redis/parser.js:20:19)
    at JavascriptRedisParser.execute (/Users/manasamishra/xlabprojects/manas-fork/redis-cluster-ioredis/node_modules/redis-parser/lib/parser.js:542:14)
    at Socket.<anonymous> (/Users/manasamishra/xlabprojects/manas-fork/redis-cluster-ioredis/node_modules/ioredis/built/redis/event_handler.js:107:26)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
```

I believe this thing is failing in 2nd time as I have passed maxRedirections as 1.

**Comment by andrewkuk** [comment] 2019-05-11 09:19
Hi! I'm had the same issue. Is any updates?

**Comment by andrewkuk** [comment] 2019-05-11 11:43
Also want to add that BLPOP command blocks connection until something new will be added to list.
And it looks like library use same connection to update slots https://github.com/luin/ioredis/blob/master/lib/cluster/index.ts#L611, and as connection is blocked by BLPOP command there will be timeout and library will close this connection after timeout.

**Comment by manasa-ei** [comment] 2019-05-13 06:39
@luin Any update on the above issue?

**Comment by RidgeA** [comment] 2019-05-13 08:09
@luin is it reasonable to use a separate connection to discover cluster and slots ?

**Comment by luin** [comment] 2019-05-13 16:50
Sorry for the late response. `MOVED` errors are caused by the timeouts when refreshing slots with the connection that in the block mode. @manasa-ei I submitted a pull request for this issue to use a separate connection to refresh slots, as suggested by @RidgeA : https://github.com/luin/ioredis/pull/867. Could you test on it to see whether the issue has been solved?

**Comment by manasa-ei** [comment] 2019-05-14 10:31
> Sorry for the late response. `MOVED` errors are caused by the timeouts when refreshing slots with the connection that in the block mode. @manasa-ei I submitted a pull request for this issue to use a separate connection to refresh slots, as suggested by @RidgeA : #867. Could you test on it to see whether the issue has been solved?

@luin It seems it is working good with a little modification such as referring timeout function from utils_1 I think it's only a merging issue. While merging this branch this needs to be taken care as the development is done on a previous version.
Please merge it as soon as possible it will help me and others a lot.

**Closed** 2019-05-15 04:34 UTC
